### ISSUE TITLE
We should specify how to contribute to task-service

### ISSUE THREAD

**Issue by cgreene** [cognoma/task-service#1]
The parent project's contributions file is here:
https://github.com/cognoma/cognoma/blob/master/CONTRIBUTING.md

**Comment by awm33** [comment]
@cgreene That all looks applicable to me. Do we just want to link to that in the README or place a copy in this repo?

**Comment by dhimmel** [comment]
I'd recommend creating a `CONTRIBUTING.md` file because GitHub [will automatically](https://help.github.com/articles/setting-guidelines-for-repository-contributors/#adding-a-contributing-file) include a banner linking to it for new pull requests and issues. In this file, you could either take the relevant parts of the `cognoma/cognoma` [guidelines](https://github.com/cognoma/cognoma/blob/master/CONTRIBUTING.md), or just link to those guidelines and explain any differences.
