### ISSUE TITLE
Consolidate core-service and task-service?

### ISSUE THREAD

**Issue by dcgoss** [cognoma/task-service#17]
Looking through the codebases, I keep wondering whether we could transfer task-service as an app to the core-service repo. Is it really necessary to run two separate django servers and databases for core-service and task-service? Wondering what y'all think. Tagging @dhimmel @awm33

**Comment by dhimmel** [comment]
@dcgoss I don't have a strong opinion. I believe @awm33 saw benefits to a having a separate service. But I'll defer to you what the best way forward is.

**Comment by awm33** [comment]
@dcgoss @dhimmel There can be benefits to a separate service if the project grew much larger in scope. But given the projects progression over the last year, I think it's safe to combine them. Since there's a 1:1 ratio between classifiers and tasks, you could even just move the task management columns directly over to the classifier table.

**Comment by dcgoss** [comment]
Planning to go ahead with the consolidation. See https://github.com/cognoma/core-service/issues/73 and https://github.com/cognoma/core-service/pull/74.
